//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantoTomas.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesorMateria
    {
        public int IdProfesorMateria { get; set; }
        public int IdProfesor { get; set; }
        public int IdMateria { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
